#NOTE: 23.07.2016 17:16:08
ACCEL_Z_D,0.0
ACCEL_Z_FILT_HZ,10.0
ACCEL_Z_IMAX,400.0
ALT_DELAY,23.0
INAV_TC_XY,1.0
INAV_TC_Z,1.0
K1_XY,3.0
K1_Z,3.0
K2_XY,3.0
K2_Z,3.0
K3_XY,1.0
K3_Z,1.0
POS_XY_P,1.0
POS_Z_P,0.9
SYSID_MYGCS,0
SYSID_SW_TYPE,0
SYSID_THISMAV,0
THR_ACCEL_I,0.4000000059604645
THR_ACCEL_P,0.5
THR_MID,1470.0
VEL_XY_I,0.5
VEL_XY_IMAX,1000.0
VEL_XY_P,1.5
VEL_Z_P,8.4
XY_DELAY,3.0
